
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always



apiVersion: v1
kind: Pod
metadata:
  name: redis-storage
spec:
  containers:
  - name: redis-storage
    image: redis:alpine
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
    
    
    apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
    - port: 3036
      nodePort: 30036
      name: http
  selector:
    name: mysql
    
    
    
   apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: hr-web-app
spec:
  selector:
    matchLabels:
      app: hr-web-app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: hr-web-app
        tier: frontend
    spec:
      containers:
      - name: hr-web-app
        image: kodekloud/webapp-color
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
            
            
            
     
            
 Create a service messaging-service to expose the messaging application within the cluster on port 6379.

apiVersion: v1kind: Service
metadata:
  name: messaging-service
  labels:
      app: messaging
      role: master
      tier: msg
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
      app: messaging
      role: master
      tier: msg
      
      

            
    
    
