apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment #A Deployment named nginx-deployment is created
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx #field defines how the Deployment finds which Pods to manage
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

